//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Projects/mapcss-net/tools/./../tools/tmp/antlr-5663a48348b5457c932f4c6f3f0109ae/MapCssParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MapCss.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MapCssParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMapCssParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.stylesheet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStylesheet([NotNull] MapCssParser.StylesheetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] MapCssParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.metaBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetaBlock([NotNull] MapCssParser.MetaBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.ruleSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleSet([NotNull] MapCssParser.RuleSetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.selectorGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectorGroup([NotNull] MapCssParser.SelectorGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelector([NotNull] MapCssParser.SelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.selectorChain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectorChain([NotNull] MapCssParser.SelectorChainContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.combinator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCombinator([NotNull] MapCssParser.CombinatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.simpleSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleSelector([NotNull] MapCssParser.SimpleSelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.selectorAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectorAtom([NotNull] MapCssParser.SelectorAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement([NotNull] MapCssParser.ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.zoomSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitZoomSpec([NotNull] MapCssParser.ZoomSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.selectorSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectorSuffix([NotNull] MapCssParser.SelectorSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.pseudoClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPseudoClass([NotNull] MapCssParser.PseudoClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.classSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassSelector([NotNull] MapCssParser.ClassSelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.subPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubPart([NotNull] MapCssParser.SubPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.attributeFilter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeFilter([NotNull] MapCssParser.AttributeFilterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.attributeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeTest([NotNull] MapCssParser.AttributeTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.attrExistence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrExistence([NotNull] MapCssParser.AttrExistenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.attrKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrKey([NotNull] MapCssParser.AttrKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.attrOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrOp([NotNull] MapCssParser.AttrOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrValue([NotNull] MapCssParser.AttrValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.bareWord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBareWord([NotNull] MapCssParser.BareWordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] MapCssParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] MapCssParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.setStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetStatement([NotNull] MapCssParser.SetStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.setItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetItem([NotNull] MapCssParser.SetItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.propertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyDeclaration([NotNull] MapCssParser.PropertyDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.valueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueList([NotNull] MapCssParser.ValueListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyName([NotNull] MapCssParser.PropertyNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprList([NotNull] MapCssParser.ExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] MapCssParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.ternaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTernaryExpr([NotNull] MapCssParser.TernaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.logicalOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpr([NotNull] MapCssParser.LogicalOrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.logicalAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpr([NotNull] MapCssParser.LogicalAndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpr([NotNull] MapCssParser.EqualityExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpr([NotNull] MapCssParser.RelationalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpr([NotNull] MapCssParser.AdditiveExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpr([NotNull] MapCssParser.MultiplicativeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] MapCssParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpr([NotNull] MapCssParser.PrimaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] MapCssParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] MapCssParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MapCssParser.literalString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralString([NotNull] MapCssParser.LiteralStringContext context);
}
} // namespace MapCss.Parser
