//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Projects/mapcss-net/tools/./../tools/tmp/antlr-5663a48348b5457c932f4c6f3f0109ae/MapCssParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MapCss.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MapCssParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMapCssParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.stylesheet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStylesheet([NotNull] MapCssParser.StylesheetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.stylesheet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStylesheet([NotNull] MapCssParser.StylesheetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MapCssParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MapCssParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.metaBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetaBlock([NotNull] MapCssParser.MetaBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.metaBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetaBlock([NotNull] MapCssParser.MetaBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.ruleSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleSet([NotNull] MapCssParser.RuleSetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.ruleSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleSet([NotNull] MapCssParser.RuleSetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.selectorGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectorGroup([NotNull] MapCssParser.SelectorGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.selectorGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectorGroup([NotNull] MapCssParser.SelectorGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector([NotNull] MapCssParser.SelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector([NotNull] MapCssParser.SelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.selectorChain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectorChain([NotNull] MapCssParser.SelectorChainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.selectorChain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectorChain([NotNull] MapCssParser.SelectorChainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.combinator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCombinator([NotNull] MapCssParser.CombinatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.combinator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCombinator([NotNull] MapCssParser.CombinatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.simpleSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleSelector([NotNull] MapCssParser.SimpleSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.simpleSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleSelector([NotNull] MapCssParser.SimpleSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.selectorAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectorAtom([NotNull] MapCssParser.SelectorAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.selectorAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectorAtom([NotNull] MapCssParser.SelectorAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement([NotNull] MapCssParser.ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement([NotNull] MapCssParser.ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.zoomSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterZoomSpec([NotNull] MapCssParser.ZoomSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.zoomSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitZoomSpec([NotNull] MapCssParser.ZoomSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.selectorSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectorSuffix([NotNull] MapCssParser.SelectorSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.selectorSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectorSuffix([NotNull] MapCssParser.SelectorSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.pseudoClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPseudoClass([NotNull] MapCssParser.PseudoClassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.pseudoClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPseudoClass([NotNull] MapCssParser.PseudoClassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.classSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassSelector([NotNull] MapCssParser.ClassSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.classSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassSelector([NotNull] MapCssParser.ClassSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.subPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubPart([NotNull] MapCssParser.SubPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.subPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubPart([NotNull] MapCssParser.SubPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.attributeFilter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeFilter([NotNull] MapCssParser.AttributeFilterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.attributeFilter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeFilter([NotNull] MapCssParser.AttributeFilterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.attributeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeTest([NotNull] MapCssParser.AttributeTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.attributeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeTest([NotNull] MapCssParser.AttributeTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.attrExistence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrExistence([NotNull] MapCssParser.AttrExistenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.attrExistence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrExistence([NotNull] MapCssParser.AttrExistenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.attrKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrKey([NotNull] MapCssParser.AttrKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.attrKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrKey([NotNull] MapCssParser.AttrKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.attrOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrOp([NotNull] MapCssParser.AttrOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.attrOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrOp([NotNull] MapCssParser.AttrOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrValue([NotNull] MapCssParser.AttrValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrValue([NotNull] MapCssParser.AttrValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.bareWord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBareWord([NotNull] MapCssParser.BareWordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.bareWord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBareWord([NotNull] MapCssParser.BareWordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] MapCssParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] MapCssParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] MapCssParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] MapCssParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.setStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetStatement([NotNull] MapCssParser.SetStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.setStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetStatement([NotNull] MapCssParser.SetStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.setItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetItem([NotNull] MapCssParser.SetItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.setItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetItem([NotNull] MapCssParser.SetItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.propertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyDeclaration([NotNull] MapCssParser.PropertyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.propertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyDeclaration([NotNull] MapCssParser.PropertyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.valueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueList([NotNull] MapCssParser.ValueListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.valueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueList([NotNull] MapCssParser.ValueListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyName([NotNull] MapCssParser.PropertyNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyName([NotNull] MapCssParser.PropertyNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprList([NotNull] MapCssParser.ExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprList([NotNull] MapCssParser.ExprListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] MapCssParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] MapCssParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.ternaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTernaryExpr([NotNull] MapCssParser.TernaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.ternaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTernaryExpr([NotNull] MapCssParser.TernaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.logicalOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpr([NotNull] MapCssParser.LogicalOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.logicalOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpr([NotNull] MapCssParser.LogicalOrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.logicalAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpr([NotNull] MapCssParser.LogicalAndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.logicalAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpr([NotNull] MapCssParser.LogicalAndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpr([NotNull] MapCssParser.EqualityExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpr([NotNull] MapCssParser.EqualityExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpr([NotNull] MapCssParser.RelationalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpr([NotNull] MapCssParser.RelationalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpr([NotNull] MapCssParser.AdditiveExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpr([NotNull] MapCssParser.AdditiveExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpr([NotNull] MapCssParser.MultiplicativeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpr([NotNull] MapCssParser.MultiplicativeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] MapCssParser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] MapCssParser.UnaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpr([NotNull] MapCssParser.PrimaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpr([NotNull] MapCssParser.PrimaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] MapCssParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] MapCssParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] MapCssParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] MapCssParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MapCssParser.literalString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralString([NotNull] MapCssParser.LiteralStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MapCssParser.literalString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralString([NotNull] MapCssParser.LiteralStringContext context);
}
} // namespace MapCss.Parser
